"""Build and validate strictly generic public queries from approved mappings only."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any, Mapping

from app.business_impact.external_context.models import PublicResearchTopic


class QueryPolicyError(ValueError):
    """Safe policy rejection that never echoes a rejected outbound query."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code; self.message = message; super().__init__(f"{code}: {message}")


@dataclass(frozen=True, slots=True)
class PublicQueryGuardConfig:
    minimum_length: int
    maximum_length: int
    forbidden_literals: frozenset[str]
    forbidden_patterns: tuple[re.Pattern[str], ...]
    allowed_characters: re.Pattern[str]
    mappings: Mapping[tuple[str, str], tuple[tuple[str, ...], tuple[str, ...]]]

    @classmethod
    def from_files(cls, query_policy_path: str | Path, topic_mapping_path: str | Path) -> "PublicQueryGuardConfig":
        try:
            policy = json.loads(Path(query_policy_path).read_text(encoding="utf-8")); mapping = json.loads(Path(topic_mapping_path).read_text(encoding="utf-8"))
            requirements = policy["query_requirements"]
            entries: dict[tuple[str, str], tuple[tuple[str, ...], tuple[str, ...]]] = {}
            for item in mapping["mappings"]:
                key = (str(item["canonical_rule_id"]), str(item["condition_id"])); entries[key] = (tuple(str(x) for x in item["research_topics"]), tuple(str(x) for x in item["preferred_source_ids"]))
            config = cls(int(requirements["minimum_length"]), int(requirements["maximum_length"]), frozenset(str(x).casefold() for x in policy["forbidden_literals"]), tuple(re.compile(str(x)) for x in policy["forbidden_patterns"]), re.compile(str(policy["allowed_character_pattern"])), entries)
        except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
            raise QueryPolicyError("QUERY_POLICY_LOAD_FAILED", "Approved query policy or topic mapping could not be loaded.") from exc
        if not config.mappings or config.minimum_length < 1 or config.maximum_length < config.minimum_length:
            raise QueryPolicyError("QUERY_POLICY_INVALID", "Approved query policy is invalid.")
        return config


class PublicQueryGuard:
    """Only emits configuration-owned generic topics; direct user/LLM text is impossible."""

    def __init__(self, config: PublicQueryGuardConfig) -> None: self._config = config

    def build_topics(self, *, canonical_rule_id: str, condition_id: str) -> tuple[PublicResearchTopic, ...]:
        """Build generic public topics from one approved mapping key only."""
        try: templates, source_ids = self._config.mappings[(canonical_rule_id, condition_id)]
        except KeyError as exc: raise QueryPolicyError("TOPIC_MAPPING_NOT_FOUND", "No approved generic public-research mapping exists for this condition.") from exc
        topics = tuple(self._topic(canonical_rule_id, condition_id, template, source_ids, position) for position, template in enumerate(templates))
        return topics

    def validate_topic(self, topic: PublicResearchTopic) -> None:
        """Defence in depth before every connector request; rejects arbitrary topics."""
        self._validate_query(topic.query_text)
        if not any(topic.query_text == template and tuple(topic.approved_source_ids) == source_ids for templates, source_ids in self._config.mappings.values() for template in templates):
            raise QueryPolicyError("QUERY_NOT_APPROVED_TEMPLATE", "Outbound public query was not generated by an approved template.")

    def _topic(self, rule_id: str, condition_id: str, text: str, source_ids: tuple[str, ...], position: int) -> PublicResearchTopic:
        self._validate_query(text)
        digest = sha256(f"{rule_id}|{condition_id}|{position}|{text}".encode()).hexdigest()[:24]
        return PublicResearchTopic(topic_id=f"topic-{digest}", query_text=text, approved_source_ids=list(source_ids), purpose="Approved generic public context retrieval.")

    def _validate_query(self, query: str) -> None:
        text = " ".join(query.split())
        lowered = text.casefold()
        if len(text) < self._config.minimum_length or len(text) > self._config.maximum_length or not self._config.allowed_characters.fullmatch(text):
            raise QueryPolicyError("QUERY_REJECTED", "Outbound public query violates configured length or character policy.")
        if any(token in lowered for token in self._config.forbidden_literals) or any(pattern.search(text) for pattern in self._config.forbidden_patterns):
            raise QueryPolicyError("QUERY_REJECTED", "Outbound public query contains prohibited internal or sensitive terminology.")
